baseURL = "http://example.org/"
languageCode = "en-us"
title = "Blank"
theme = "blank"

[Params]
    name = "Blank|..."
    description = "A simple home page site."
    favicon = "/images/favicon.ico"
    avatar = "/images/avaatr.jpg"

[[params.links]]
name = "Site A"
icon = ""
url = "http://a.example.org/"


[[params.links]]
name = "Site B"
icon = ""
url = "http://b.example.org/"
